name: Triggered Country EPG
on:
  repository_dispatch:
    types: [build_epg]
  workflow_dispatch:
    inputs:
      country:
        description: 'Country Code (e.g., CA)'
        required: true
        default: 'CA'

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: iptv-org/epg
          path: grabber
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Grabber
        run: cd grabber && npm install

      - name: Create Config
        # Determine country from dispatch payload OR manual input
        run: |
          COUNTRY_CODE=${{ github.event.client_payload.country || github.event.inputs.country }}
          python3 filter_channels.py $COUNTRY_CODE
          echo "COUNTRY=$COUNTRY_CODE" >> $GITHUB_ENV

      - name: Run Grabber
        run: |
          cd grabber
          npm run grab -- --channels=../channels.json --output=../epg_db/${{ env.COUNTRY }}.xml

      - name: Deploy to Repo
        run: |
          git config --global user.name "EPG-Bot"
          git add epg_db/*.xml
          git commit -m "Updated EPG for ${{ env.COUNTRY }}" || exit 0
          git push
